stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node
  script: 
    - echo "Start building App"
    - npm install
    - npm build
    - echo "Build successfully!"

test:
  stage: test
  image: node
  dependencies:
    - build
  script:
    - npm test

deploy:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  before_script:
    - apk add curl nodejs npm
    - npm install -g heroku
  dependencies:
    - build
    - test
  script:
  - docker build -f Dockerfile -t web .
  - docker login -u $HEROKU_USER -p $HEROKU_API_KEY registry.heroku.com
  - docker tag web registry.heroku.com/gymshop-frontend/web
  - docker push registry.heroku.com/gymshop-frontend/web
  - heroku container:release web --app gymshop-frontend
  only:
    - master
