stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node
  script: 
    - echo "Start building App"
    - npm install
    - npm build
    - echo "Build successfully!"

test:
  stage: test
  image: node
  script:
    - echo "Testing App"

deploy:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  script:
  - docker build -f Dockerfile --iidfile imageid.txt -t registry.heroku.com/gymshopapi-product-service .
  - docker login -u $HEROKU_USER -p $HEROKU_API_KEY registry.heroku.com
  - docker push registry.heroku.com/gymshopapi-product-service
  only:
    - master